"""
Triple Filter Strategy Module.

Combines SMA Trend Filter, MACD Momentum Crossover, and RSI Boundaries
to generate high-probability trading signals for NSE stocks.

Owner: GT (Quant Lead)
Phase: Phase 3 Active
"""

import logging

import numpy as np
import pandas as pd
from ta.momentum import RSIIndicator
from ta.trend import MACD, SMAIndicator

# Setup logging according to CLAUDE.md standards
logger = logging.getLogger(__name__)


def generate_triple_filter_signals(
	df_input: pd.DataFrame,
) -> tuple[pd.Series, pd.Series]:
	"""Calculate indicators and return entry/exit boolean matrices.

	Args:
	    df_input (pd.DataFrame): Dataframe containing standard historical OHLCV data.

	Returns:
	    tuple[pd.Series, pd.Series]: (entries, exits) as boolean series for vectorbt.
	"""
	try:
		# Create a local copy to avoid modifying the original dataframe in place
		df = df_input.copy()

		# Flatten columns if yfinance returns a MultiIndex layout
		if isinstance(df.columns, pd.MultiIndex):
			df.columns = df.columns.get_level_values(0)

		# 1. Calculate Indicators using 'ta' library
		df["SMA50"] = SMAIndicator(close=df["Close"], window=50).sma_indicator()

		macd_calc = MACD(
			close=df["Close"], window_slow=26, window_fast=12, window_sign=9
		)
		df["MACD_diff"] = macd_calc.macd_diff()

		df["RSI"] = RSIIndicator(close=df["Close"], window=14).rsi()

		# Clean NaN rows generated by rolling window logic before matrix computation
		df.dropna(subset=["SMA50", "MACD_diff", "RSI"], inplace=True)

		if df.empty:
			logger.warning(
				"DataFrame is empty after dropping rolling window NaN values."
			)
			return pd.Series(dtype=bool), pd.Series(dtype=bool)

		# 2. Optimized Entry Logic Setup (Higher threshold for strong momentum)
		entries = (df["Close"] > df["SMA50"]) & (df["MACD_diff"] > 0) & (df["RSI"] > 45)

		# 3. Exit Logic Setup (MACD death cross)
		exits = df["MACD_diff"] < 0

		logger.info("Signals generated successfully. Total data points: %d", len(df))
		return entries, exits

	except Exception as e:
		logger.error("Failed to generate triple filter signals: %s", e)
		return pd.Series(dtype=bool), pd.Series(dtype=bool)


if __name__ == "__main__":
	# Smoke test execution loop for internal validation
	logging.basicConfig(level=logging.INFO)
	logger.info("Running manual smoke test with mock data arrays...")

	dates = pd.date_range(start="2026-01-01", periods=100, freq="D")
	mock_df = pd.DataFrame(
		{
			"Open": np.random.randn(100) + 200,
			"High": np.random.randn(100) + 205,
			"Low": np.random.randn(100) + 195,
			"Close": np.random.randn(100) + 200,
			"Volume": np.random.randint(1000, 5000, size=100),
		},
		index=dates,
	)

	test_entries, test_exits = generate_triple_filter_signals(mock_df)
	print("Smoke Test Execution Complete! Entries found:", test_entries.sum())
