"""
Triple Filter Strategy Module.

Combines SMA Trend Filter, MACD Momentum Crossover, and RSI Boundaries
to generate high-probability trading signals for NSE stocks.

Owner: GT (Quant Lead)
Phase: Phase 3 Active
"""

import logging

import numpy as np
import pandas as pd
import vectorbt as vbt
from ta.momentum import RSIIndicator
from ta.trend import MACD, SMAIndicator

# Setup logging according to CLAUDE.md standards
logger = logging.getLogger(__name__)


def generate_triple_filter_signals(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
	"""Calculate indicators and return entry/exit boolean matrices.

	Args:
	    df (pd.DataFrame): Dataframe containing standard historical OHLCV data.

	Returns:
	    tuple[pd.Series, pd.Series]: (entries, exits) as boolean series for vectorbt.
	"""
	try:
		# 1. Calculate Indicators using 'ta' library
		df["SMA50"] = SMAIndicator(close=df["Close"], window=50).sma_indicator()

		macd_calc = MACD(
			close=df["Close"], window_slow=26, window_fast=12, window_sign=9
		)
		df["MACD_diff"] = macd_calc.macd_diff()

		df["RSI"] = RSIIndicator(close=df["Close"], window=14).rsi()

		# Clean NaN rows generated by rolling window logic before backtesting
		df.dropna(inplace=True)

		if df.empty:
			logger.warning("DataFrame is empty after dropping NaN values.")
			return pd.Series(), pd.Series()

		# 2. Strict Entry Logic Setup (3 Filters)
		entries = (
			(df["Close"] > df["SMA50"])
			& (df["MACD_diff"] > 0)
			& (df["RSI"] > 40)
			& (df["RSI"] < 65)
		)

		# 3. Exit Logic Setup (MACD death cross)
		exits = df["MACD_diff"] < 0

		logger.info("Signals generated successfully. Total data points: %d", len(df))
		return entries, exits

	except Exception as e:
		logger.error("Failed to generate triple filter signals: %s", e)
		return pd.Series(), pd.Series()


if __name__ == "__main__":
	# Smoke test execution loop for internal validation
	logging.basicConfig(level=logging.INFO)
	logger.info("Running manual smoke test with mock data arrays...")

	# Create 100 rows of random price data to test if architecture runs
	dates = pd.date_range(start="2026-01-01", periods=100, freq="D")
	mock_df = pd.DataFrame(
		{
			"Open": np.random.randn(100) + 200,
			"High": np.random.randn(100) + 205,
			"Low": np.random.randn(100) + 195,
			"Close": np.random.randn(100) + 200,
			"Volume": np.random.randint(1000, 5000, size=100),
		},
		index=dates,
	)

	test_entries, test_exits = generate_triple_filter_signals(mock_df)
	print("Smoke Test Execution Complete! Entries found:", test_entries.sum())
