import logging

import pandas as pd
import yfinance as yf
from ta.momentum import RSIIndicator
from ta.trend import MACD

# Pristine production logger setup
logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

VALID_PERIODS = {"1d", "5d", "1mo", "3mo", "6mo", "1y", "2y", "5y", "10y", "ytd", "max"}


def calculate_vwap(df: pd.DataFrame) -> pd.Series:
	"""Calculates Volume Weighted Average Price (VWAP) for the given dataframe."""
	# Typical Price = (High + Low + Close) / 3
	typical_price = (df["High"] + df["Low"] + df["Close"]) / 3
	# VWAP = Cumulative(Typical Price * Volume) / Cumulative(Volume)
	tp_v = typical_price * df["Volume"]
	cum_tp_v = tp_v.cumsum()
	cum_v = df["Volume"].cumsum()

	# Handle division by zero edge case safely
	vwap = cum_tp_v / cum_v.replace(0, 1)
	return vwap


def fetch_and_analyze(ticker: str, period: str = "1y") -> pd.DataFrame | None:
	"""Runs Guneet's Proprietary Multi-Indicator (RSI + MACD + VWAP) Trading Strategy.

	Args:
	    ticker (str): Yahoo Finance ticker symbol (must end with '.NS').
	    period (str): Historical lookback horizon array. Defaults to "1y".

	Returns:
	    pd.DataFrame | None: Dataframe containing computed indicators and final alpha alpha signals.
	"""
	# 1. INPUT DEFENSIVE SANITIZATION
	if not ticker.lower().endswith(".ns"):
		logger.warning(f"⚠️ Ticker '{ticker}' is missing .NS suffix. Skipping.")
		return None

	if period not in VALID_PERIODS:
		logger.warning(f"⚠️ Invalid period context '{period}'. Processing halted.")
		return None

	logger.info(
		f"🛰️ Ingesting streaming architecture for proprietary evaluation: {ticker}"
	)

	try:
		# 2. RAW HISTORICAL DATA INGESTION
		stock = yf.Ticker(ticker)
		df = stock.history(period=period)

		if df.empty:
			logger.warning(f"⚠️ Data extraction failed for {ticker}. Frame is empty.")
			return None

		# 3. ADVANCED PROP QUANT INDICATORS CALCULATIONS
		# Calculate VWAP
		df["VWAP"] = calculate_vwap(df)

		# Calculate RSI (14-period standard window)
		df["RSI"] = RSIIndicator(close=df["Close"], window=14).rsi()

		# Calculate MACD metrics
		macd_engine = MACD(
			close=df["Close"], window_fast=12, window_slow=26, window_sign=9
		)
		df["MACD_Line"] = macd_engine.macd()
		df["MACD_Signal"] = macd_engine.macd_signal()

		# Clean NaN records generated by rolling indicators
		df.dropna(inplace=True)

		if df.empty:
			logger.warning(
				"⚠️ Mathematical truncation error: Insufficient row count after computing indicators."
			)
			return None

		# 4. CAPTURE LATEST VECTOR STATE FOR STRATEGY EVALUATION
		latest_row = df.iloc[-1]
		price = float(latest_row["Close"])
		vwap_val = float(latest_row["VWAP"])
		rsi_val = float(latest_row["RSI"])
		macd_l = float(latest_row["MACD_Line"])
		macd_s = float(latest_row["MACD_Signal"])

		# 5. AUTOMATED 3-WAY MULTI-INDICATOR SIGNAL COMPILER
		# Bullish condition: Price > VWAP and RSI rising from low, and MACD crossing above Signal Line
		is_bullish = (
			(price > vwap_val) and (rsi_val > 40 and rsi_val < 65) and (macd_l > macd_s)
		)

		# Bearish condition: Price < VWAP and RSI overextended or dropping, and MACD crossing below Signal Line
		is_bearish = (price < vwap_val) and (rsi_val < 60) and (macd_l < macd_s)

		if is_bullish:
			signal = "🟢 STRONG BULLISH BUY (RSI + MACD + VWAP CONFIRMED)"
		elif is_bearish:
			signal = "🔴 STRONG BEARISH SELL (TREND COLLAPSED)"
		else:
			signal = "🟡 NEUTRAL POSITION (STRATEGY IS WAITING FOR SYSTEM ALIGNMENT)"

		# 6. HIGH-END EXECUTIVE METRIC LOG REPORT
		logger.info("\n" + "🔥" * 25)
		logger.info(f"🔱 GUNEET'S PROPRIETARY QUANT ALPHA ENGINE: {ticker}")
		logger.info("🔥" * 25)
		logger.info(f"• Current Asset Price    :  💵 INR {price:.2f}")
		logger.info(f"• Dynamic Real-time VWAP :  📊 INR {vwap_val:.2f}")
		logger.info(f"• Relative Strength (RSI):  ⚡ {rsi_val:.2f} (Base-100)")
		logger.info(
			f"• MACD System Vector     :  📈 Line: {macd_l:.4f} | Signal: {macd_s:.4f}"
		)
		logger.info(f"• CORE STRATEGY RECKONING:  {signal}")
		logger.info("🔥" * 25 + "\n")

		return df

	except Exception as e:
		logger.error(f"❌ Structural breakdown in strategy execution engine: {str(e)}")
		return None


if __name__ == "__main__":
	# Execute strategy natively on high liquidity assets
	fetch_and_analyze("RELIANCE.NS", period="1y")
